export const SCENE_DIMENSIONS_RATIO = 16 / 9;
export const MODEL_MAX_HEIGHT_LENGTH = 2.5;
export const MODEL_MAX_WIDTH_LENGTH = 2.5 * SCENE_DIMENSIONS_RATIO;
export const TARGET_SPAWN_POSITION_ON_Y_AXIS = -1;
export const GROUND_ANTI_Z_COLLISION_DISTANCE = 0.001;
